"""Repository rule for extracting assembly version from AssemblyInfo.cs"""

def _version_from_assemblyinfo_impl(repository_ctx):
    """
    Reads AssemblyInfo.cs and extracts the version number.

    This repository rule parses the AssemblyVersion attribute from a C# AssemblyInfo.cs
    file and makes it available as a Bazel variable for use in BUILD files.

    The extracted version is exposed via a VERSION.bzl file that can be loaded in BUILD files.
    """

    # Read the AssemblyInfo.cs file
    assemblyinfo_label = repository_ctx.attr.assemblyinfo_file
    assemblyinfo_path = repository_ctx.path(assemblyinfo_label)

    if not assemblyinfo_path.exists:
        fail("AssemblyInfo.cs not found at: {}".format(assemblyinfo_path))

    content = repository_ctx.read(assemblyinfo_path)

    # Extract version using regex pattern
    # Matches: [assembly: AssemblyVersion("1.2.3.4")]
    # Also supports: [assembly: AssemblyVersion ( "1.2.3.4" )]
    # Also supports commented lines: //[assembly: AssemblyVersion("1.2.3.4")]
    # Uses the LAST match found (in case there are example/commented versions before the real one)
    version = None
    for line in content.split("\n"):
        # Remove leading/trailing whitespace and comment markers
        line = line.strip()

        # Remove leading // if present (support commented attributes)
        if line.startswith("//"):
            line = line[2:].strip()

        # Look for AssemblyVersion attribute
        if "AssemblyVersion" in line and "[assembly:" in line:
            # Extract version string between quotes
            # Find the opening quote
            start = line.find('"')
            if start == -1:
                continue

            # Find the closing quote
            end = line.find('"', start + 1)
            if end == -1:
                continue

            candidate_version = line[start + 1:end]

            # Skip example versions with wildcards
            if "*" in candidate_version:
                continue

            # Use this version (will be overridden if a later one is found)
            version = candidate_version

    if not version:
        fail("Could not find [assembly: AssemblyVersion(\"...\")] in {}".format(assemblyinfo_path))

    # Validate version format (should be X.Y.Z or X.Y.Z.W)
    parts = version.split(".")
    if len(parts) < 2 or len(parts) > 4:
        fail("Invalid version format: {}. Expected format: X.Y.Z or X.Y.Z.W".format(version))

    # Normalize to 4-part version (add .0 if needed)
    # Starlark doesn't support while loops, so use list comprehension
    parts = parts + ["0"] * (4 - len(parts))

    normalized_version = ".".join(parts)

    # Generate VERSION.bzl file that exports the version
    repository_ctx.file("VERSION.bzl", """# Auto-generated by version_from_assemblyinfo repository rule
# Source: {source}
# Do not edit manually - modify {source} instead

VERSION = "{version}"
""".format(
        source = assemblyinfo_label,
        version = normalized_version,
    ))

    # Generate BUILD.bazel file
    repository_ctx.file("BUILD.bazel", """# Auto-generated by version_from_assemblyinfo repository rule

exports_files(["VERSION.bzl"])
""")

    # Also create a simple VERSION text file for debugging
    repository_ctx.file("VERSION", normalized_version)

version_from_assemblyinfo = repository_rule(
    implementation = _version_from_assemblyinfo_impl,
    attrs = {
        "assemblyinfo_file": attr.label(
            mandatory = True,
            allow_single_file = [".cs"],
            doc = "Label pointing to AssemblyInfo.cs file (e.g., '//Properties:AssemblyInfo.cs')",
        ),
    },
    doc = """
Extracts assembly version from AssemblyInfo.cs and makes it available in Bazel.

This repository rule parses the [assembly: AssemblyVersion("...")] attribute
from a C# AssemblyInfo.cs file and generates a VERSION.bzl file that can be
loaded in BUILD files.

Example usage in WORKSPACE:

    load("@rules_dotnet_framework//dotnet:defs.bzl", "version_from_assemblyinfo")

    version_from_assemblyinfo(
        name = "assembly_version",
        assemblyinfo_file = "//Properties:AssemblyInfo.cs",
    )

Example usage in BUILD.bazel:

    load("@assembly_version//:VERSION.bzl", "VERSION")

    net_vsto_addin(
        name = "MyAddin.dll",
        version = VERSION,
        ...
    )

This ensures a single source of truth for version numbers, avoiding duplication
between AssemblyInfo.cs and BUILD files.
"""
)
