"""File staging action for WiX installer builds"""

load("@rules_dotnet_framework//dotnet/private:paths.bzl", "paths")

def stage_vsto_files_for_wix(
        dotnet,
        name,
        vsto_library,
        include_vsto_utilities = True):
    """
    Creates a staging directory with all files needed for WiX installer build.

    This mimics the structure of MSBuild's bin/Release directory, which WiX
    expects as the source directory ($(var.SourceDir) in .wxs files).

    Args:
        dotnet: The dotnet context from dotnet_context()
        name: Base name for the staging directory
        vsto_library: DotnetLibrary provider from net_vsto_addin target
        include_vsto_utilities: Whether to include VSTO Utilities DLLs (default: True)

    Returns:
        Directory (tree artifact) containing staged files
    """

    # Create staging directory
    staging_dir = dotnet.actions.declare_directory(name + "_staging")

    # Collect all files to stage
    files_to_stage = []

    # 1. Main VSTO assembly
    files_to_stage.append(vsto_library.result)

    # 2. PDB file (if available)
    if hasattr(vsto_library, "pdb") and vsto_library.pdb:
        files_to_stage.append(vsto_library.pdb)

    # 3. Manifests (.dll.manifest, .vsto)
    # Note: These should be generated by net_vsto_addin rule
    # For now, we'll look for them in runfiles
    for runfile in vsto_library.runfiles.to_list():
        basename = paths.basename(runfile.path)
        # Include .manifest, .vsto, .config files
        if basename.endswith(".manifest") or basename.endswith(".vsto") or basename.endswith(".config"):
            files_to_stage.append(runfile)

    # 4. Transitive dependencies (NuGet packages, referenced assemblies)
    for dep in vsto_library.transitive:
        if hasattr(dep, "result") and dep.result:
            files_to_stage.append(dep.result)

        # Also include dependency runfiles (additional DLLs)
        if hasattr(dep, "runfiles"):
            for runfile in dep.runfiles.to_list():
                # Only include DLLs, not all runfiles
                if runfile.path.endswith(".dll"):
                    files_to_stage.append(runfile)

    # 5. VSTO Utilities (if requested)
    # Note: These are typically NOT in the staging directory
    # They are referenced via bindpath in WiX
    # But we'll provide an option to include them if needed
    # (Handled separately in WiX build action)

    # Create a script to copy files to staging directory
    # We need to preserve the flat structure (all files in one directory)
    copy_script = "#!/bin/bash\n"
    copy_script += "set -e\n"
    copy_script += "mkdir -p {}\n".format(staging_dir.path)

    for f in files_to_stage:
        # Copy each file to staging directory (flat structure)
        basename = paths.basename(f.path)
        copy_script += "cp -f {} {}/{}\n".format(f.path, staging_dir.path, basename)

    # Write the copy script
    script_file = dotnet.actions.declare_file(name + "_stage.sh")
    dotnet.actions.write(
        output = script_file,
        content = copy_script,
        is_executable = True,
    )

    # Execute the staging action
    dotnet.actions.run(
        executable = script_file,
        inputs = files_to_stage,
        outputs = [staging_dir],
        mnemonic = "WixStageFiles",
        progress_message = "Staging files for WiX installer build: {}".format(name),
    )

    return staging_dir

def stage_vsto_files_for_wix_windows(
        ctx,
        name,
        vsto_library):
    """
    Windows-specific file staging for WiX builds.

    Uses Windows commands (cmd.exe) instead of bash.

    Args:
        ctx: Rule context
        name: Base name for the staging directory
        vsto_library: DotnetLibrary provider from net_vsto_addin target

    Returns:
        Directory (tree artifact) containing staged files
    """

    # Create staging directory
    staging_dir = ctx.actions.declare_directory(name + "_staging")

    # Collect all files to stage
    files_to_stage = []

    # 1. Main VSTO assembly
    files_to_stage.append(vsto_library.result)

    # 2. PDB file (if available)
    if hasattr(vsto_library, "pdb") and vsto_library.pdb:
        files_to_stage.append(vsto_library.pdb)

    # 3. VSTO manifest files from addin outputs (not in runfiles)
    # These are generated by net_vsto_addin and are in DefaultInfo.files
    if hasattr(ctx.attr, "vsto_addin") and ctx.attr.vsto_addin:
        for output_file in ctx.attr.vsto_addin[DefaultInfo].files.to_list():
            basename = paths.basename(output_file.path)
            # Include .manifest, .vsto, .config files
            if (basename.endswith(".manifest") or
                basename.endswith(".vsto") or
                basename.endswith(".config")):
                files_to_stage.append(output_file)

    # 4. Transitive dependencies
    for dep in vsto_library.transitive:
        if hasattr(dep, "result") and dep.result:
            files_to_stage.append(dep.result)

    # 5. Runfiles (additional DLLs)
    for runfile in vsto_library.runfiles.to_list():
        basename = paths.basename(runfile.path)
        # Include DLLs and PDBs (manifests handled above)
        if (basename.endswith(".dll") or
            basename.endswith(".pdb")):
            files_to_stage.append(runfile)

    # Create Windows batch script to copy files
    # Use %~dp0 to get the script directory, then navigate to execroot
    # Script location: bazel-out/<config>/bin/Setup.Wix/<name>_stage.bat
    # Execroot is 4 directories up: ..\..\..\..\
    copy_script = "@echo off\n"
    copy_script += "REM Navigate to execroot from script location\n"
    copy_script += "set EXECROOT=%~dp0..\\..\\..\\..\n"
    copy_script += "cd /d \"%EXECROOT%\"\n"
    copy_script += "\n"
    copy_script += "if not exist {} mkdir {}\n".format(
        staging_dir.path.replace("/", "\\"),
        staging_dir.path.replace("/", "\\"),
    )

    for f in files_to_stage:
        src_path = f.path.replace("/", "\\")
        dst_path = staging_dir.path.replace("/", "\\")
        basename = paths.basename(f.path)
        copy_script += "copy /Y \"{}\" \"{}\\{}\"\n".format(src_path, dst_path, basename)

    # Write the batch script
    script_file = ctx.actions.declare_file(name + "_stage.bat")
    ctx.actions.write(
        output = script_file,
        content = copy_script,
        is_executable = True,
    )

    # Execute the staging action
    # Note: Convert path to Windows backslashes for cmd.exe
    script_path_win = script_file.path.replace("/", "\\")
    ctx.actions.run(
        executable = "cmd.exe",
        arguments = ["/c", script_path_win],
        inputs = files_to_stage + [script_file],
        outputs = [staging_dir],
        mnemonic = "WixStageFiles",
        progress_message = "Staging files for WiX installer build: {}".format(name),
    )

    return staging_dir
